---
- hosts: "{{ hosts }}"
  gather_facts: true
  connection: ssh
  remote_user: root
  vars:
    - jdk_tar: 
    - java_home: /usr/local/jdk

  tasks:
    - name: 获取java_home目录信息
      tags: get-javahome
      stat:
        path: "{{ java_home }}"
      register: info

    - name: "检查java_home: {{ java_home }} 是否存在"
      tags: check-javahome
      fail:
        msg: "{{ java_home }} 已经存在"
      when: info.stat.exists and info.stat.isdir
    
    - name: 上传jdk包并解压
      tags: upload
      unaricvh:
        src: files/jdk-11-xxx.tar.gz
        dest:
        
    - name: 添加环境变量
      tags: add_env
      copy:
        content: export PATH="{{ java_home }}/bin:$PATH" 
        dest: /etc/profile.d/java.sh

    - name: 获取版本信息
      tags: 
      command: "{{ java_home }}"/bin/java -version
      register: version

    - name: 打印版本信息
      debug:
        var: version