
---
- hosts: rabbitmq
  gather_facts: false
  remote_user: root
  connection: ssh    # default

  tasks:
  - name: Upload rabbitmq-serve, socat, erlang package to remote hosts.
    copy: src={{ filename }} dest=/tmp/{{ filename }}
    tags: upload_file
    loop:
      - socat-1.7.2.3-1.el6.x86_64.rpm
      - erlang-20.3.8.23-1.el6.x86_64.rpm
      - rabbitmq-server-3.7.6-1.el6.noarch.rpm

  - name: sync /etc/hosts to remote hosts (override)
    copy: src=hosts dest=/etc/hosts

  - name: install socat erlang rabbitmq-server
    command: cd /usr/local/src && \
             rpm -ivh socat-1.7.2.3-1.el6.x86_64.rpm \
             erlang-20.3.8.23-1.el6.x86_64.rpm \
             rabbitmq-server-3.7.6-1.el6.noarch.rpm   
  
  - name: sync rabbitmq-env.conf and rabbitmq.config to remote hosts
    copy: src="{{item}}" dest=/etc/rabbitmq
    loop:
      - rabbitmq.config
      - rabbitmq-env.conf

  - name: create direcotry
    shell: mkdir /data/rabbitmq/{mnesia,schema,plugins} -p && chown rabbitmq.rabbitmq /data/rabbitmq -R