---
- hosts: "{{ host }}"
  gather_facts: true
  remote_user: root
  connection: ssh   # default
  
  tasks:
    - name: For RHEL/Centos system initialization on remote hosts.
      tags: system_init
      script: files/system_init.sh
      when: ansible_os_family == "RedHat"