# 为root用户添加ssh密钥对，免密钥登陆
---
- hosts: "{{ host }}"
  gather_facts: false
  remote_user: root
  connection: ssh    # defalut

  # 对远程主机root的用户免密登录
  tasks:
    - name: Upload the id_rsa.pub file to remote hosts.
      tags: upload_rsa.pub
      copy: src=~/.ssh/id_rsa.pub dest=/tmp

    - name: Write to authorized_keys
      tags: write_authorized_keys
      shell: cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys
