
# 给所有的主机安装zookeeper
--- 
- hosts: "{{ remote }}"
  gather_facts: false
  remote_user: root
  
  vars:
    - ZOO_HOME: /opt/zookeeper
    - ZOO_LOG_DIR: /data/logs/zookeeper
    - ZOO_DATA_DIR: /data/zookeeper

  tasks:                                           # 代表一组任务(tasks)
    - name: upload zookeeper to remote server      # task1
      tags:
      copy: src=files/zookeeper-3.4.6.tar.gz  dest=/tmp/zookeeper-3.4.6.tar.gz

    - name: unzip zookeeper-3.4.6.tar.gz           # task2
      tags:
      shell: cd /usr/local/src && tar xf zookeeper-3.4.6.tar.gz && mv zookeeper-3.4.6 {{ ZOO_HOME }}
    
    - name: create data and logs directory         # task3
      file: path={{item}} state=directory mode='0755' recurse=True
      loop:
        - {{ ZOO_DATA_DIR }}
        - {{ ZOO_LOG_DIR }}
    
    - name: configure                              # task4
      template: src=templates/zoo.j2 dest={{ ZOO_HOME }}/conf/zoo.cfg

    - name: set zkEnv                              # task5
      template: src=templates/zkEnv.j2 dest={{ ZOO_HOME }}/bin/zkEnv.sh mode=0744

    - name: SystemV                                # task6
      template: src=templates/zookeeper.j2 dest=/etc/init.d/zookeeper mode=0744

    - name: start zookeeper                        # task7
      service: name=zookeeper state=started enabled=yes
