# 安装jdk，默认为jdk11.0.6(lts)版本，如果想安装不同的版本，请将版本包放入当前的files目录
# 然后把vars中的jdk_tar变量定义为你的版本包的包名

---
- hosts: "{{ host }}"
  gather_facts: false
  remote_user: root
  connection: ssh    # default
  
  vars:
    - jdk_tar: jdk-11.0.6_linux-x64_bin.tar.gz
    - jdk_dir: "{{ jdk_tar.split('.tar.gz')[0] }}" # jdk-version_linux-64_bin
    - java_home: /usr/local/jdk
    - temp_dir: /usr/local/src

  tasks:
    - name: 获取java_home目录信息
      tags: get-javahome
      stat:
        path: "{{ java_home }}"
      register: info

    - name: "检查java_home: {{ java_home }}是否存在"
      tags: check-javahome
      fail:
        msg: "java_home: {{ java_home }}已经存在"
      when: info.stat.exists and info.stat.isdir

    - name: "上传jdk"
      tags: upload-java
      unarchive:
        src: "files/{{ jdk_tar }}"
        dest: "{{ temp_dir }}" 

    - name: "移动包至{{ java_home }}"
      tags: mv-javahome
      copy:
        src: "{{ temp_dir }}/{{ jdk_dir }}/"
        dest: "{{ java_home }}"
        remote_src: yes

    # 覆盖
    - name: 添加java_环境变量
      tags: add-env
      copy:
        content: export PATH={{ java_home }}/bin:$PATH
        dest: /etc/profile.d/java.sh
        
    - name: 获取版本信息
      tags: version
      ignore_errors: yes
      command: "{{ java_home }}/bin/java -version"
      register: version

    - name: 打印版本信息
      tags: get-version
      debug: 
        msg: "{{ version.stderr_lines[0] }}"

    - name: 删除解压后的文件
      tags: del-temp
      file:
        path: "{{ temp_dir }}/{{ jdk_dir }}"
        state: absent
...